name: 'GitHub Actions result'

on:
  push:
    branches: 
      - master
  schedule:
   - cron: '20 * * * *'
jobs:
  result-spider:
    runs-on: ubuntu-latest
    steps:
      - name: set_time
        run: |
          cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          date
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: 'Install dependencies'
        run: python -m pip install --upgrade pip
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
      - name: 'Working'
        timeout-minutes: 350
        run: |
          bash ./main.sh
          cp result/result.json oldhot/$(date +%Y%m%d%H%M%S).json
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "$(date +%Y%m%d%H%M%S)" -a
      - name: 'Push changes'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
#       - name: 'Create a Release'
#         uses: elgohr/Github-Release-Action@v3.1
#         env:
#           GITHUB_TOKEN: ${{ secrets.TOKEN }}
#         with:
#           args: result
